#%RAML 1.0 NamedExample
          {
            "first_name": "Betelehem",
            "last_name": "Tilahun",
            "account_no": "2343423453",
            "phone_no": "+251848585858",
            "card_no": "O123",
            "OrangeaccountID": "123"
          }